# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
  pod 'netfox'
end

target 'TheMovieDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  common_pods
  # Pods for TheMovieDB

end



